INSERT INTO pois (name, description, price, map_id, latitude, longitude, created_at, custom_order, image)
VALUES
('Ramen Isshin','Ramen Isshin means One Heart One Ramen. Bringing true authentic Ramen to the city of Toronto. Our happiness is your happiness and we always want to make you smile.​ We offer a variety of bowls that are very unique in flavours, textures and taste. We want you to have our Isshin experience and leave satisfied and always smiling!', 5, 3, 43.6565, -79.4070, now (), 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/LvnYnumInn7dmCewmQsU3w/o.jpg'),
('Whelans Gate','Whelans Gate has been around in one form or another since 1992. Whelans Gate is now a gastro pub; offering fresh, homemade and locally sourced comfort food with excellent cocktails and a selection of Irish and local micro-brews.', 3, 3, 43.6553, -79.4564, now (), 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/oteLM8B-IMa3EcG6GYQvEw/o.jpg'),
('Banjara','I love Banjara! It is impressive how well they cater the flavours at all spice levels and can please both the traditional Indian customers and non Indian palette alike! All items I have tried are great. The butter chicken and karahi lamb were delicious! This is a Toronto staple and most likely the best Indian restaurant around.', 5, 2, 43.6629, -79.4220, now (), 3, 'https://s3-media0.fl.yelpcdn.com/bphoto/vm22yfk2J3iPeUzRKkDa5w/o.jpg'),
('La Carnita', 'Locally designed with the help of some of Toronto best street style artists, La Carnita is the spot to enjoy delicious tacos, a handful of churros, run through a mixtape, and wash it all down with a fresh cocktail or beer. At the heart of what we do is always to serve up a dynamic menu, and connect with the community through our love of art and music.', 4, 1, 43.6561, -79.4092, now(), 1, 'https://s3-media0.fl.yelpcdn.com/bphoto/RptRROj_pHR1es5n0m0E_w/o.jpg'),
('Playa Cabana', 'All those amazing tacos and burritos and enchiladas and all but I gotta start this review saying that my favourite one is the AL PASTOR! Delicious pork marinated in this not too spicy sauce, grilled with pineapples, on a soft shell taco with guacamole and red onions, ouffff its amazing!', 3, 1, 43.6761, -79.4016, now(), 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/eleLP29pepclL6SRHMAyzA/o.jpg'),
('Seven Lives', 'Seven Lives is synonymous with Baja-style tacos, for good reason. The tiny Kensington Market spot often has a lineup snaking out the door as hordes of hungry taco seekers wait for their very own Gobernador, the places signature dish.', 3, 1, 43.6543, -79.4005, now(), 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/eleLP29pepclL6SRHMAyzA/o.jpg'),
('Pukka', 'Pukka is a forward-thinking take on Indian cuisine that is unparalleled in Canada. Pukka is family-style sharing plates with full-size flavours. The menu takes you on a journey through decadent tastes, while maintaining a lightness that enchants the palette. The culinary team elevates the typical Indian curry into clean, modern bites that wow both the eyes and the taste buds.', 3, 2, 43.6811, -79.4288, now(), 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/qT2v_IPE1-J-PMei_npuvg/o.jpg'),
('Lahore Tikka House', 'If your taste buds are looking for a Traditional/Modern Pakistani/North Indian Cuisine with sizzling BBQ and delicious Karahi[Curries], then Lahore Tikka House is the place for you. We are one of Toronto most popular and palatial Northern Indian and Pakistani restaurants. We are so much more than just a restaurant. We are a community, a family, and a legacy.', 3, 2, 43.6716, -79.3249, now(), 2, 'https://s3-media0.fl.yelpcdn.com/bphoto/LfD7LlQaTW8UMJazwjxmMQ/o.jpg')
